common: &common
  paypal:
    id: "pgupta@enbake.com"
    sandbox_url : "https://www.sandbox.paypal.com/cgi-bin/webscr"
    paypal_url : "https://www.sandbox.paypal.com/cgi-bin/webscr"
    account : "pgupta@enbake.com"
    success_url : "/"
  mailchimp:
    merchant_id: "14b2beddd47e086d798ea9276beef9df-us8"

development:
  <<: *common

test:
  <<: *common
production:
  <<: *common
