common: &common
  paypal:
    id: "pgupta@enbake.com"
    sandbox_url : "https://www.sandbox.paypal.com/cgi-bin/webscr"
    paypal_url : "https://www.sandbox.paypal.com/cgi-bin/webscr"
    account : "pgupta@enbake.com"
    success_url : "/"

development:
  <<: *common

test:
  <<: *common
production:
  <<: *common
